services:
  db:
    container_name: "${DB_NAME}"
    image: postgres:14-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
